### ISSUE TITLE
也许你该关注下这个

### ISSUE THREAD

**Issue by xlievo** [waitaction/Json2Sql#1]
nodejs的jsonorm
http://docs.sequelizejs.com/en/latest/docs/querying/

**Comment by xlievo** [comment]
建议你根据他的规范来实现，毕竟好的规范是好的开始，兼容性也会更好。你懂的

**Comment by waitaction** [comment]
对方使用的是js，而这套是用在C#的。C#将对像序列化为JSON，格式是这样的 { key1:value1,key2:value2 } ,
然而它使用了这样的方式
```
{
  scope1: {
    where: {
      firstName: 'bob',
      age: {
        $gt: 20
      }
    },
    limit: 2
  },
  scope2: {
    where: {
      age: {
        $gt: 30
      }
    },
    limit: 10
  }
} 
```
它是  
   age: {
        $gt: 20
      }
而我大概是
$gt:{
  age:20
}
安卓前端传到后端的是json数据，安卓端使用的是java语言，用的是 class ，序列化为json也是 { age:20  } 这样的方式。要知道，安卓端是有一套动态ORM框架，直接通过这种json2sql的方式远程操作数据库。所以这种方案    age: { $gt: 20   } 是一开始被我否定掉的，后来才改为 $gt:{  age:20 } 这种方式。
我没有时间去整理文档。但是我可以说，我这套比较适用于 C#/JAVA 。它那套是为js而生的。
代码是开源的，你可以拿来修改，去兼容它的标准。

**Comment by waitaction** [comment]
设想一下，APP端与服务器通讯时是怎么传数据的？ 
会有一个接口，比如是 query/userinfo   ,  post的内容是 {  name:"xiaoming" , age:18   }  ， 但是数据库字段增加，两端同时改。
所以才会有json2sql这种设想 ,接口是 query    { userinfo:{ name:"xiaoming" , age:18 , city:"sz"  } }  ,
这种方式就是 { Equ:{ userinfo:{ name:"xiaoming" , age:18 , city:"sz"  } } }  的简写,
Equ可以换成 { Greater:{ userinfo:{ name:"xiaoming" , age:18 , city:"sz"  } } }  ，而用Greater比$rt语义更加清晰，安卓程序员鬼知道$rt是啥。userinfo里面就是类成员，安卓端也很好序列化。
所以，语言不一样，决定着思维方式不一样。

**Comment by waitaction** [comment]
推荐一个轻量级的js orm框架
https://github.com/waitaction/TypeScriptDapper 

使用方式与C#的Dapper类似

**Comment by xlievo** [comment]
我仔细的研究比较了一下，你说的是对的，赞同你的观点：我这套比较适用于 C#/JAVA 。它那套是为js而生的。js的东西确实不能很好的为C#/java服务
原谅我在没有过多的深入下冒昧的提问！感谢分享

**Comment by xlievo** [comment]
json化的查询应该是个趋势，这个项目应该要有一个很好的活跃度，希望你有更多的精力完善它，谢谢
